apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: dt26-ambulance-ufe
  namespace: dt26-hospital
spec:
  imageRepositoryRef:
    name: dt26-ambulance-ufe # referuje ImageRepository z predchádzajúceho kroku
  filterTags:
      pattern: "main.*" # vyberie všetky verzie, ktoré začínajú na main- (napr. main-20240315.1200)
  policy:
    alphabetical:
      order: asc