apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: dt26-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/xtruhlar/dt26-ambulance-gitops