apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: image-updater
  namespace: dt26-hospital
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: gitops-repo # repozitár ktorý sme konfigurovali v predchádzajúcej kapitole
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcd_bot
      messageTemplate: |
        Automated image update

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Changes:
        {{- range $_, $change := .Changed.Changes }}
        - {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{- end }}
    push:
      branch: main
  update:
    path: ./components/version-developers  # cesta kde chceme automaticky upraviť našu konfiguráciu
    strategy: Setters