apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/part-of: dt26-hospital

namespace: dt26-hospital

resources:
- prepare.kustomization.yaml
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml