apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prepare
  namespace: dt26-hospital
spec:
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: envoy-gateway
      namespace: envoy-gateway-system
    - apiVersion: apps/v1
      kind: Deployment
      name: polyfea-controller
      namespace: polyfea
  interval: 120s
  path: clusters/localhost/prepare
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo