apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dt26-gitops-repo
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/xtruhlar/dt26-ambulance-gitops
