apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dt26-install
  namespace: wac-hospital
spec:
  wait: true
  interval: 120s
  path: clusters/wac-aks/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: dt26-gitops-repo
