apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: davidtruhlar7/dt26-ambulance-ufe
  newName: davidtruhlar7/dt26-ambulance-ufe # {"$imagepolicy":  "dt26-hospital:dt26-ambulance-ufe:name"}
  newTag: main.20260505.1826 # {"$imagepolicy": "dt26-hospital:dt26-ambulance-ufe:tag"}
