apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    wac-fiit.github.io/component: backend

resources:
- 'https://github.com/xtruhlar/dt26-ambulance-webapi//deployments/kustomize/install' # ?ref=v1.0.1
- openapi-ui.service.yaml
- http-route.yaml

patches:
- path: patches/ambulance-webapi.deployment.yaml
