apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dt26-hospital  # chceme tieto objekty umiestniť do `dt26-hospital` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch
labels:
- pairs:
    app.kubernetes.io/part-of: dt26-hospital

resources:
- ../../../apps/dt26-ambulance-ufe
