apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt26-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /dt26-openapi
            - name: BASE_URL
              value: /dt26-openapi-ui
