apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- webcomponent-link.yaml
- webcomponent-content.yaml
- microfrontend.yaml

labels:
- pairs:
    app.kubernetes.io/component: dt26-ambulance-ufe
    wac-fiit.github.io/component: frontend