apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: dt26-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: "Projekt - Dávid Truhlář"
    - name: short-headline
      value: "Vzdialené vyšetrenia"
    - name: supporting-text
      value: |
        Správa vzdialených vyšetrení a konzultácií pacientov
    - name: material-icon
      value: home_health
    - name: href
      value: ./dt26-ambulance-ufe
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content