apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: dt26-ambulance-ufe-content
spec:
  microFrontend: dt26-ambulance-ufe
  element: dt26-ambulance-ufe-app
  attributes:
    - name: base-path
      value: /dt26-ambulance-ufe/
    - name: api-base
      value: /dt26-api
    - name: ambulance-id
      value: dt26-ambulance
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?dt26-ambulance-ufe(/.*)?$"